# Generated by Django 5.0.1 on 2024-05-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_alter_medicine_category_alter_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
